// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "controllers/application"

import BrainDumpController from "controllers/brain_dump_controller"
application.register("brain-dump", BrainDumpController)

import CookieConsentController from "controllers/cookie_consent_controller"
application.register("cookie-consent", CookieConsentController)

import DropdownController from "controllers/dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "controllers/hello_controller"
application.register("hello", HelloController)

import PomodoroController from "controllers/pomodoro_controller"
application.register("pomodoro", PomodoroController)

import TaskController from "controllers/task_controller"
application.register("task", TaskController)
