// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BrainDumpController from "./brain_dump_controller"
application.register("brain-dump", BrainDumpController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PomodoroController from "./pomodoro_controller"
application.register("pomodoro", PomodoroController)

import TaskController from "./task_controller"
application.register("task", TaskController)
